version: '3'

volumes:
  profesor-db-data:

networks:
  profesor-network:
    driver: bridge

services:
  profesor:
    build:
      context: .
    ports:
      - 80:5000
    volumes:
      - .:/app
    depends_on:
      - profesor_db
    restart: always
    networks:
      - profesor-network

  profesor_db:
    image: postgres
    volumes:
      - profesor-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    restart: always
    networks:
      - profesor-network